In [2]:
import pandas as pd

In [3]:
customers = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_customers_dataset.csv")
geolocation = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_geolocation_dataset.csv")
order_items = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_order_items_dataset.csv")
order_payments = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_order_payments_dataset.csv")
order_reviews = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_order_reviews_dataset.csv")
orders = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_orders_dataset.csv")
products = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_products_dataset.csv")
sellers = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_sellers_dataset.csv")
product_categories = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/product_category_name_translation.csv")

In [4]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [5]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [6]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [7]:
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [8]:
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [9]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [10]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [11]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [12]:
product_categories.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [13]:
customers.duplicated().sum()

np.int64(0)

In [14]:

geolocation.duplicated().sum()

np.int64(261831)

In [15]:
order_items.duplicated().sum()

np.int64(0)

In [16]:
order_payments.duplicated().sum()

np.int64(0)

In [17]:
order_reviews.duplicated().sum()

np.int64(0)

In [18]:
orders.duplicated().sum()

np.int64(0)

In [19]:
products.duplicated().sum()

np.int64(0)

In [20]:
sellers.duplicated().sum()

np.int64(0)

In [21]:
product_categories.duplicated().sum()

np.int64(0)

In [24]:
customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [25]:
geolocation.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [ ]:
order_items.dtypes

product_category_name            object
product_category_name_english    object
dtype: object

In [27]:
order_payments.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [28]:
order_reviews.dtypes

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [29]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [30]:
products.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [31]:
sellers.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [32]:
product_categories.dtypes

product_category_name            object
product_category_name_english    object
dtype: object

In [34]:
order_reviews['review_score'].value_counts()

review_score
5    57328
4    19142
1    11424
3     8179
2     3151
Name: count, dtype: int64

In [38]:
order_items['price'].min()

0.85

In [39]:
order_items['freight_value'].min()

0.0

In [41]:
order_payments['payment_value'].min()

0.0

In [42]:
order_payments['payment_installments'].min()

0

In [43]:
products['product_weight_g'].min()

0.0

In [44]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [45]:
(order_items['price'] == 0).sum()

np.int64(0)

In [46]:
(order_items['freight_value'] < 0).sum()

np.int64(0)

In [47]:
(order_payments['payment_value'] == 0).sum()

np.int64(9)

In [48]:
order_payments[order_payments['payment_value'] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [50]:
order_payments[order_payments['payment_type'] == 'not_defined']

,order_id,payment_sequential,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

In [52]:
(order_payments['payment_installments'] == 0).sum()

np.int64(2)

In [53]:
order_payments[order_payments['payment_installments'] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [54]:
(products['product_weight_g'] == 0).sum()

np.int64(4)

In [55]:
products[products['product_weight_g'] == 0]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
9769,81781c0fed9fe1ad6e8c81fca1e1cb08,cama_mesa_banho,51.0,529.0,1.0,0.0,30.0,25.0,30.0
13683,8038040ee2a71048d4bdbbdc985b69ab,cama_mesa_banho,48.0,528.0,1.0,0.0,30.0,25.0,30.0
14997,36ba42dd187055e1fbe943b2d11430ca,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0
32079,e673e90efa65a5409ff4196c038bb5af,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0

In [56]:
(products['product_length_cm'] == 0).sum()

np.int64(0)

In [57]:
(products['product_height_cm'] == 0).sum()

np.int64(0)

In [58]:
(products['product_width_cm'] == 0).sum()

np.int64(0)

In [59]:
(products['product_weight_g'] < 0).sum()

np.int64(0)

In [60]:
customers['customer_id'].duplicated().sum()

np.int64(0)

In [62]:
orders['order_id'].duplicated().sum()

np.int64(0)

In [63]:
products['product_id'].duplicated().sum()

np.int64(0)

In [64]:
sellers['seller_id'].duplicated().sum()

np.int64(0)

In [65]:
order_payments['order_id'].duplicated().sum()

np.int64(4446)

In [66]:
order_reviews['review_id'].duplicated().sum()

np.int64(814)

In [67]:
order_items['order_id'].duplicated().sum()

np.int64(13984)

In [68]:
orders['customer_id'].isin(customers['customer_id']).all()

np.True_

In [69]:
order_items['order_id'].isin(orders['order_id']).all()

np.True_

In [70]:
order_payments['order_id'].isin(orders['order_id']).all()

np.True_

In [71]:
order_reviews['order_id'].isin(orders['order_id']).all()

np.True_

In [72]:
order_items['product_id'].isin(products['product_id']).all()

np.True_

In [73]:
order_items['seller_id'].isin(sellers['seller_id']).all()

np.True_