In [8]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [3]:
customers = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_customers_dataset.csv")
geolocation = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_geolocation_dataset.csv")
order_items = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_order_items_dataset.csv")
order_payments = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_order_payments_dataset.csv")
order_reviews = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_order_reviews_dataset.csv")
orders = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_orders_dataset.csv")
products = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_products_dataset.csv")
sellers = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/olist_sellers_dataset.csv")
product_categories = pd.read_csv("C:/Users/saran/guvi project/cart2insights/data/raw/product_category_name_translation.csv")

In [4]:
order_reviews[['review_comment_title', 'review_comment_message']].isnull().sum()

review_comment_title      87656
review_comment_message    58247
dtype: int64

In [5]:
order_reviews['review_comment_title'] = order_reviews['review_comment_title'].fillna('No title')

In [6]:
order_reviews['review_comment_message'] = order_reviews['review_comment_message'].fillna('No comment')

In [7]:
order_reviews[['review_comment_title', 'review_comment_message']].isnull().sum()

review_comment_title      0
review_comment_message    0
dtype: int64

In [8]:
orders[orders['order_approved_at'].isnull()]['order_status'].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [9]:
orders[orders['order_delivered_carrier_date'].isnull()]['order_status'].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [10]:
orders[orders['order_delivered_customer_date'].isnull()]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [11]:
products[products['product_category_name'].isnull()].isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                1
product_length_cm               1
product_height_cm               1
product_width_cm                1
dtype: int64

In [12]:
products[
    products['product_category_name'].isnull() &
    products['product_weight_g'].isnull()
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
products = products.dropna(
    subset=['product_category_name',
            'product_name_lenght',
            'product_description_lenght',
            'product_photos_qty',
            'product_weight_g',
            'product_length_cm',
            'product_height_cm',
            'product_width_cm']
)

In [14]:
products.shape

(32340, 9)

In [15]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [16]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [17]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [18]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [19]:
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [20]:
order_reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [21]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [22]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [23]:
orders['order_purchase_timestamp'] = pd.to_datetime(
    orders['order_purchase_timestamp']
)

In [24]:
orders['order_purchase_timestamp'].dtype

dtype('<M8[ns]')

In [25]:
orders['order_approved_at'] = pd.to_datetime(
    orders['order_approved_at']
)

In [26]:
orders['order_approved_at'].dtype

dtype('<M8[ns]')

In [28]:
orders['order_delivered_carrier_date'] = pd.to_datetime(
    orders['order_delivered_carrier_date']
)
orders['order_delivered_carrier_date'].dtype

dtype('<M8[ns]')

In [29]:
orders['order_delivered_customer_date'] = pd.to_datetime(
    orders['order_delivered_customer_date']
)
orders['order_delivered_customer_date'].dtype

dtype('<M8[ns]')

In [30]:
orders['order_estimated_delivery_date'] = pd.to_datetime(
    orders['order_estimated_delivery_date']
)
orders['order_estimated_delivery_date'].dtype

dtype('<M8[ns]')

In [31]:
order_items.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [33]:
order_items['shipping_limit_date'] = pd.to_datetime(
    order_items['shipping_limit_date']
)
order_items['shipping_limit_date'].dtype

dtype('<M8[ns]')

In [34]:
order_reviews.dtypes

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [35]:
order_reviews['review_creation_date'] = pd.to_datetime(
    order_reviews['review_creation_date']
)

order_reviews['review_answer_timestamp'] = pd.to_datetime(
    order_reviews['review_answer_timestamp']
)
order_reviews[['review_creation_date', 'review_answer_timestamp']].dtypes

review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [36]:
order_payments.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [37]:
products.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [38]:
customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [39]:
sellers.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [40]:
geolocation.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [41]:
product_categories.dtypes

product_category_name            object
product_category_name_english    object
dtype: object

In [42]:
order_payments[order_payments['payment_value'] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [43]:
order_payments[order_payments['payment_installments'] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [44]:
products[products['product_weight_g'] == 0]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
9769,81781c0fed9fe1ad6e8c81fca1e1cb08,cama_mesa_banho,51.0,529.0,1.0,0.0,30.0,25.0,30.0
13683,8038040ee2a71048d4bdbbdc985b69ab,cama_mesa_banho,48.0,528.0,1.0,0.0,30.0,25.0,30.0
14997,36ba42dd187055e1fbe943b2d11430ca,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0
32079,e673e90efa65a5409ff4196c038bb5af,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0

In [47]:
products.loc[products['product_weight_g'] == 0, 'product_weight_g'] = np.nan
products['product_weight_g'].isnull().sum()

np.int64(4)

In [48]:
(products['product_weight_g'] < 0).sum()

np.int64(0)

In [49]:
(products['product_length_cm'] == 0).sum()

np.int64(0)

In [50]:
(products['product_height_cm'] == 0).sum()

np.int64(0)

In [51]:
(products['product_width_cm'] == 0).sum()

np.int64(0)

In [52]:
(order_items['price'] < 0).sum()

np.int64(0)

In [53]:
(order_items['freight_value'] < 0).sum()

np.int64(0)

In [54]:
order_reviews['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [55]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [56]:
order_payments['payment_type'].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [58]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              4
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [59]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [60]:
order_items['product_id'].isin(products['product_id']).all()

np.False_

In [61]:
missing_product_ids = order_items.loc[
    ~order_items['product_id'].isin(products['product_id']),
    'product_id'
].unique()

missing_product_ids

array(['ff6caf9340512b8bf6d2a2a6df032cfa',
       'a9c404971d1a5b1cbc2e4070e02731fd',
       '5a848e4ab52fd5445cdc07aab1c40e48',
       '41eee23c25f7a574dfaf8d5c151dbb12',
       'e10758160da97891c2fdcbc35f0f031d',
       '76d1a1a9d21ab677a61c3ae34b1b352f',
       'fbb1cfc2810efabf3235eccf4530f4ae',
       '9f69acd4da62618a3f6365b732d00ccd',
       'ea11e700a343582ad56e4c70e966cb36',
       '8c0bd0d6526379599b74a3a006d4c124',
       'ad88641611c35ebd59ecda07a9f17099',
       '8d39a63db6a98e40571f486e0c711cf7',
       '32a99bb84ae79a55c0e446afc9310e1e',
       'b1d207586fca400a2370d50a9ba1da98',
       '00ab8a8b9fe219511dc3f178c6d79698',
       '17823ffd2de8234f0e885a71109613a4',
       'b36f3c918c91478c4559160022d3f14e',
       '1b7384e0f9f5e4cb914cd3f5535a4cab',
       '0fa699aaa0a38aa5d1de8e7fe04d2204',
       '4914f8796af2ecd359fd8f44b9b92339',
       '1b0e39ec889889ea1d492603d8512bfb',
       '5f5ee6e720308ce93007ce17c0835883',
       'f58e45b16a42a325c144eb2c46a2bc57',
       '6ab9d49c399f239bc88ea28c7568213f',
       'ceda8168fb181a91487d6e924f42334f',
       '0c877471e35049402bca235e06cb8063',
       'c230b471b7e21ff9060e68ee154afd70',
       'b29fcbd778387a0218e2f058e57bce75',
       '8a26f391ab8b209f67d87dd358f6f004',
       '6f3ec6fc14615aaed51a2e900868a3cf',
       'e878662b68e175a58b5951e44574d5c8',
       'ed906d6a6b38da71e48a5a0037939bfe',
       '8a0c7c7b32d023b5c6cefe93d16e4a99',
       '3373d1ed7bf5f3187f110c0e9e40a02b',
       'b72e2daf4a916d46eb0076071027d05b',
       '17e7128a33dae59e32be411b7b4921b5',
       'e49a57a6afd465b7d3cd109daf09ca98',
       '4e0d588f8e002f2bad9cbe0b8f66f6f6',
       'a2d0ef58f86a42fa9d456709cb00c0b2',
       '583916a5dae918f5e89baec139141c54',
       '3abf2d4698bf245577543ea01d9c7f16',
       '67c4868694e75a87d7d0417c14fc26a3',
       '0502d1a36be75bd36b452f31c6ed264a',
       '50f39d42ee3c1155a39f330b0b53c735',
       'e0f33a3329af6716a0bb47fd7a664439',
       '0bb7d5c406dd6affef3cd4f5d6744844',
       '99fdc04e6b6614fa8899cefafe793fa7',
       '7899001d8d8933d11d0f18ec5943f79e',
       '45a15b38cc3c0514717a1de673c6193c',
       'e7dceae66fa56a4b4c9d62e72945b17d',
       'c4777fd2beb13264f71e768685823987',
       'f0ea71b6e2ab4cb3bd8f5ba522a25a56',
       '90a57d62c9b9f884fae33a10dff953b4',
       '033fe931444d66d788d53aca5b7b22d5',
       'b02a3f9824b29932f36a74d811f1b14c',
       '3d4784f9a07ca5de370c86800589c860',
       '75f54c6aa3a4ccb9ab44fae693c21418',
       'b8c2cf7e813b0eb7ec62f7459217b22c',
       '46d418ab71bf88eeaa978665d4b0f693',
       '4d2481b021cc6916e6c45615ee2d7638',
       '9b13a7d22318479913aa50b379d41726',
       'b22a81bf3aad8a40e439f0f55dcbdce0',
       'f9b1795281ce51b1cf39ef6d101ae8ab',
       '3b60d513e90300a4e9833e5cda1f1d61',
       '5eb564652db742ff8f28759cd8d2652a',
       '124f74f703e88efe001a10bfa718b6ff',
       '52a5346c9dae9cd560b103875b94d123',
       '14086fd4907ab4135efce70c2cd3c013',
       '8f5b9d7258ddc83215b7efa05e73825f',
       '837f3d09b625825bd84bfccb1f51d8be',
       'f9a1a72d4069bf9570e29b9c620bef07',
       'bb80645f347f26e0a4da138c7b2745aa',
       'b20dff2518b593f3092fb7b3ba13588e',
       '81abb619b6717f1ff31f79e5d73a215b',
       'f2317e7dd5b1b4dea36595ff6db6f14b',
       '8d3367004d60f40855db4a5bbbabfdb6',
       'a14aea6067b93158e956612c50b74cfa',
       'a08ffa6ecdd0ab3c1f4fe348acc2553b',
       '3c59055b72a9160589590ca99611487e',
       'd73f1e4ad0322d8442fc9591505381aa',
       'a1804276d9941ac0733cfd409f5206eb',
       '5066fb9bf2b3db42c59f2f7732387249',
       'ce5a07feea47b22089fc735f70ae4931',
       'd0fec025748a38a25d8f8adc72e874de',
       '980a05f1865790c75cf9a22ae4771c1c',
       'fe34503c6bccf918db601aaafd4a975a',
       'f59062775ff63deba00e8b425f127e35',
       '9549bc9cccdcfb09de0bd4774b018c3d',
       '74ba0cd1f694e0751c7240443e5a038b',
       'bfa0e398bef2d28bb421d42997982cab',
       '3846c262ddb08db0ea2cc1a1685590ff',
       '82f142f09dd26762af87b2a889f6ed58',
       '4cda9d93b0a846dfdca597f1b1d19c08',
       '2873da054c3a30189c5aac7b87d3b6e9',
       '2aba8009f50472b2eda33e9e2bb3ef6f',
       '455819d0d2ccab9c6041aa8de3ae6b16',
       'd3518f8ee8c8bf28b6a1304145b50219',
       '0cf1296fa38622de944eb05701b4ff34',
       'e0520a21b848aa7efcb536bbda142e75',
       'a184d57c818939252af3b5400f55429a',
       '0b7fb806fe0194cc7eb473329c680e34',
       'e275b12a1775bcc17af5524af5ba80b4',
       '62ea5d617ff74ab3e446aa418e7f67ed',
       '1a1dba78177cbabf00a2e1eab46e62b6',
       '516f4c728fa63b7394b4a4d99a010ff6',
       '194163a8a65a48a8c95623c399a9d4a7',
       '2fc46e8ba9bbe4d062776e585b8c0057',
       '9b564ab4807c6c00dcc56a91c5e1c8a3',
       'c30302f36e15f43c1b85c9cb002028d5',
       'e891d4a9622cae3b9fc2ec558bda155b',
       'fc5dd987f12a7b823a76a44aa1ba88f6',
       'd36c8237f8a0a889aa9d6ac7816097e3',
       '0ae10ca52e6cb8745e17c11e7c43907c',
       '704a6d9f35e39b53c509c886045329ef',
       '794de06c32a626a5692ff50e4985d36f',
       '629beb8e7317703dcc5f35b5463fd20e',
       '5a670fea12f6946f0dcb3fbb9728645d',
       '3f6f946481fd39f4eda986012f6e0447',
       '0082684bb4a60a862baaf7a60a5845ed',
       '51ce723ffd19d9d8d7893b8e835bf3cf',
       '8ae1fefcfdc30ea49de246665b6d2713',
       'c73ce46ad401dcf7c05da1cc8a65dea2',
       '93305944cf8bb41c63bf59676ac2d0b3',
       '21e4321fa558327afe025bfb800a8bff',
       'e43443a05db61acfccaca5876b804ba7',
       '4257f45f6ea58aa46885ed7ef723b6c0',
       'cef16b173166d8d44b4fbf05b4b43bec',
       '0b3f73dba78abf4576c187092dc5dc81',
       'c638e232871cb1e760eaa7e724bc3eb2',
       'b690fe3d3dd6223b85382ccca04ffbde',
       '83fb98f2457985e6333f2e307adc5864',
       '6f6f3b1a96452e2fbad0cd4f7082765b',
       '751d70675dda2bae203db325227b8a3c',
       'b3f3d2afe706552a90fd99f870e4ddf5',
       '88c09dd121ebe0b119a759773d405cc4',
       '0292b46c30348496b1be04eeb440bdb5',
       '5a2a2db3896d33beec6828b898812ad5',
       '1f5542855786adc0116f56cfd6f9f830',
       '79a299827b3f285bf8aa370c12fa159a',
       '83a837a76c0753d44c7c12bcb1b96158',
       '1d94d1e0c7fb2dcf2811e093d2ca303b',
       'ed000a9f9f04376551e24de254464c9e',
       '9901b5cedc1eb8d69d16d4c3aa8c67d3',
       '7285e977b36a2243203636b240772c5e',
       '9df852a6c839bc3202227666d70c7cae',
       'f92119d44c137a84ea866dc12df68407',
       '28fff36d13d492328583ee2b1d72f78f',
       '2beea058d80efa4403a56673a219352d',
       '37e4c14527273be66b84b8836bba463b',
       'df5032e775a51867fcd72f5b742f2f33',
       'f7c7bd3105bd26ce0de4072af7159f84',
       '5f6ebc88683dcfc794febc8d8a8aeb0c',
       '9689d8153681f3d8bc3e88622c013b08',
       'fe1341006261b53f5f8415fb27772e66',
       'fcde1899043318107d8f0ae043f69bc3',
       '1b930f20f389f3e3d057b9e3e85ca83d',
       'c4ceee876c82b8328e9c293fa0e1989b',
       'fc49395ccfb1f65ab0d1352684772112',
       'eed5cbd74fac3bd79b7c7ec95fa7507d',
       '1b1654fea0a8269f9ba9a1e1258edb61',
       'a4d8f727f92014da5dd64116af14634c',
       '791052a0d5071f87efbc002b579ccb9e',
       '3aa87ff048f23ae9ac589dd73c21d98c',
       '8307d6d6781b40a6b3b4c222da56f274',
       '2f282449dadb2e59ff2afcde0bd9f393',
       '28b04f8634b7c9c6e3a41fbd0271e295',
       'c892c76504fbc267594383bd0f0d94e8',
       'd5376c3b45290c7a326584c8307ab2c4',
       '4754922e24570093f580454e5920cd34',
       '0baaa6da9c9440c4655efd0762a0edcf',
       '44ae8d3edf5612ff7a39d629d5bbb8ae',
       '06ddfdf210c7e0259854ee543215088d',
       '00d62b338366db4c4aec8547ea8f928e',
       '5b736e2bc208fe225a4f3da85e5dc63d',
       'dd9e631c9f1f8008b90fff5170d02c2a',
       'b44922681ddcd1565a9d62932f20dcfe',
       'db1d1a4569fdbae28a0d3340d907f7af',
       'aaa391b7c35a628a6318851e8e933e0b',
       'f71a7ef227514bb1feacf612102d6a19',
       '0103863bf3441460142ec23c74388e4c',
       '447540e8fcd91fc4f9b1587aed39882c',
       'c2ddba1b0149af8ce1b6b0d220f0411a',
       'e77303f7e13ee5a4ec287783bde94c70',
       'aa2b29bee083c3eb3779f39fc09527b7',
       '2ddbeb76f134690c05636162f2558594',
       '9575c58d6ba5856589c410cef0b3f0e0',
       '242a6abd32d7630b48ef5c0a1bf527eb',
       'fb34a3bfc66ae09f045f9613fdb7bb5c',
       '46b48281eb6d663ced748f324108c733',
       '88d6c305d09a6fdc1c34cb51942a280c',
       '11ea2b91f0f26a2d693ba6763a2eb4b0',
       '34e01766eefd8ee844083f3d1f21653c',
       '4941b2c06706332ebfd9072d7b1fb23c',
       'fa7fc74ae3858461908b3503b355fd5e',
       '56139431d72cd51f19eb9f7dae4d1617',
       '5d3e31adf8ff92075c3848f021abaf06',
       'cdbb028dcdcdb294fd86a808b3569c11',
       '5a5d7d4e7f23de210890506c818d2b8a',
       '13c68a908e3ec61b48544be41a74e8cd',
       '1fde73e6b6d28627ff16e222b0044b10',
       'ab1741a86f20ab3aca7dd2c347d5a9e3',
       'adf8f4e4c2e176a9e7437e484066f769',
       'e76828e87d341935c7d4e9f26420cda0',
       'd64615580eb89e5d9a6ae0e37135a5fe',
       '0a7a5763f6ee3b862ca27208f8fbbdb7',
       '8c7274c4e638e7f229007fe28aafc741',
       '6b7879a37ac2dbe5289a16706e859870',
       '19bdfd05824c29bf495c9f5408c26635',
       'f1cfcd7f3806fd98650ab8dda3b7dfea',
       'fd85f34d70edf41fbea6a3269d183e00',
       '3cc10293fcaadd63730fc96e8d136710',
       'bf1ce2996ddec3052749c74b73b02b86',
       'b52385de7f52a8dc46d4195e2f77f965',
       '3e591cbf1cec40074c24a2ce372a5b62',
       '17b9f231d057710012fe28e5a1ac5186',
       '27822f63a7f1bbbf439dfbdbec05b129',
       '22e8a1571e0f8e1aeac77c01ae28539c',
       '519693b7e29749ed7b6ad60cb07b9400',
       'f4470c119e77b79863901b5d2152fc6f',
       '626fcce994b573d0bd54d6447d5badd3',
       '6bda3bc4a9032dc7f18b635e051d0c72',
       'dcda28837e91de197266ec8d4327d0f6',
       '44e8945e17aef03daaecbc4bbab7f730',
       '4dfb5b21cf54e026b36472ea52d67e6d',
       '31dbb0d1815bdc83c93f4b3472fa7c4d',
       '0ed27993e016d4546e2038bfd75b812c',
       'e621e5b4cac0fb8cfabee7a4a64bdc52',
       'b9adb2d8377c195da59e75743dbb7133',
       'b2c888bdc2e3b970ec418f4c9f9877a3',
       '930363fe8355b51e7bb4154214246561',
       'fb09c649a144a9dfd4546612891e1f11',
       'e47eff9f97c9536c9f768f86e13252f6',
       'ad5f871bf1f82cf7aed349162ab802e6',
       'c4d92c32b2e02363d3f087c7156a523c',
       '1bd0e965122ea1485d8f7f0c6792ebe0',
       'a4fe640db0a85c68b24bf813604c6b78',
       '09337f4d317bae01dfa96e6d368eafc4',
       '39fda099b9edc21f85a80d14021579b5',
       'fcb72602e3e6f59e5fdb5c3a4a3de410',
       'a1edc55bde3207643a142f3e6074e942',
       '41f1e5a38185a9ae6090a552b712ba43',
       '9be8d8c1b3cb9e629230d4c176b14ae9',
       '88ca370ef97df0526aeaea6932a38bdd',
       'c243b9426a87ba098db1a7da1512d919',
       '9fdb63e8a7e98f5ee2c68448a0145139',
       'e952feb7c657aae141c56f208088d511',
       'e4b0320c22018a6aeacee9b991ccb1fd',
       'c8316575e7ce05609496b6d0b9bce6bd',
       'bc3d15dd90a6794ea7710f1642aae319',
       'ae9d8ccddc081b66d656332ddf9b2373',
       'be59f0b9bd1d08d096188f98168fc987',
       'b7f980dbd49d4059a8c4acbada394e4b',
       '9ce62e73b4ea1a6c74b68ba57aa1333b',
       '08a59a7c557b1b8d49e5029a337d83fd',
       '83f86eca5473b6d1c7d566223592908d',
       '5455dbe20e64b08413e0f2c451e31ab9',
       'f849624adffb78b4cd40066ecf73aaeb',
       '05feccd482d35726d6f80e60df25db86',
       '2d188e4d3435b1bf29dfd385b324de2c',
       'df07d0388563ce1b87695a6ae85898da',
       '15f773b4fea5b2ab681b02620b0c3a95',
       '62fde58e97724f8b7519f3789eefa33f',
       '19ac4a7de40be5bd72347162024983f2',
       '0ceb0bfefd73a9c9dc6f918182841cc1',
       '631cc372948b89f0211271f2546d9f44',
       '5fb61f482620cb672f5e586bb132eae9',
       'fb3d7615501eb8155531583652015360',
       '036a6272d538ae862d248339c4c9adeb',
       'ce215f864c313d0ecf9582661992f4d9',
       '8be128ce3f51211048f4b891e9303381',
       'a133d679c63597e416572ee64d9d6436',
       'cd64fc35f195d70cebe293e0b60dce33',
       '8e49e2b4aaa2a78f82c80d2e488084f6',
       '7e28b562fde0b95bd515cde17eb9bbb6',
       '51fe26bc4bb0f89f07096d8c96b35476',
       'cae7a908351ea0b7acb0086a51f6f565',
       'c17abb4b4009c10138dec784ec61ba63',
       'baded889837476e342ac1e93c87ce383',
       '3125175fa8b71940f198f68b56f992b2',
       'a61e6f38c9e407c7d764ea09d34b0a76',
       '9820e04e332fc450d6fd975befc1bc28',
       'f538ab9eecaa662135da8cb772bc8236',
       'e0cc4c7d6a254af178315aa78d7b5256',
       '21dd96fd31df21001d8e5b7a3fac9335',
       '690951ea8e8b7ac46921683da1b4707d',
       'fa51e914046aab32764c41356b9d4ea4',
       '4b63219873a41d0f93899f71f7a80a60',
       '5096c7c3620e53dda164502e228d4779',
       '72f399a2336a151acdb3a0a3b391f75a',
       'f52a0f70e54976873a4a7402349c6105',
       'ef335a744a67679ed37e8698353dfc95',
       '4432acdc80e1b1f73f9f355f12ecd60f',
       '1913e11c70ce94032c05b17bbded599a',
       'bff35d3572b474e918bb0780723240bb',
       '39e3b9b12cd0bf8ee681bbc1c130feb5',
       '18da4a6d2c9b127b43ac8616ab151aa8',
       'd85783d7c896fdb2fadbbc19c6a1c58e',
       '97077aaf1edef55f3c90f91075f92261',
       'e1c3325750402ab195a7759f01efa494',
       'c2fffbd2b50c3f612755de49109e6d97',
       '2b7f2a7cf1025b94bc5dc6c28746beaf',
       '4ba237d0c64f22e4d22ec19af9cfd1f4',
       '24776376f3b02d27ac141a1bdc46d628',
       'ebf5a1e0cf87ae9837d87ab93d47a46b',
       '05f581382fca988fec41f4a3de0e0fda',
       '26a4f62a409a78816adb31e0d729a163',
       '23df926bdc8477e1ec36c182136411a3',
       '33404a09d81156efd8d2299cf5568f1f',
       '8b0bbcbc6fab91d08a10c1fb25764bc1',
       '212cc0fa7359ab242a697a03a574f719',
       '0fe09f32709c79ba4bf19d43c4e49515',
       '9b6459fd1853c7e4422ff0bdd8184cb3',
       '1c6a5fd4bf0e4196dc0a20386c496bd3',
       'e034d967d446f193a9d72f30a282c312',
       '3fc7f2008dc11b252c0f0e51a7bea4d6',
       'de6702c748c719cbd13bb814f006ba22',
       '1e9e02777a02de03c17eb432be7daf71',
       'ea8062a20ca055f459f3a99eccdec4b5',
       '8ef13bdd5d6da4bc50df1aaa486bf922',
       '9246752373bd625f47da5e3d8b41b1dc',
       'c92a8559445ec8f63ecf90c7dd910b7d',
       '3d103df80d5d22d709244fe27bc29a8d',
       '26587700f0a79fcaa3cd891f837e284e',
       'a9d70f6d031016d058af905f309260b0',
       '05cf9ac595f28386ee763c98cbc2bad0',
       '51189083f547bae6df07c55c7b997001',
       'bac2d18d169f029e0721b8aca9c8f269',
       'fbd2a9aa1f115244e2ce115ad8eacfca',
       '8229dca25207625966da8cffda27446c',
       '7f776a76a6dce545729c997e60240ffa',
       '9d09d82a6838777302175f209dcfc4ec',
       '3eac3be4413c51ec917d2108ab24e69c',
       'c600d7f13104e8db2ca2b9fa78581409',
       'a8cb589d0aa5e6308a8fcf133ecca711',
       '68fb1d8f0c51d866116189cb07e652ea',
       'ba4a6f5b128eec53f68288f5238f9971',
       '60d1e2123927bc621354b0ab11cc8fd5',
       '7775d718fa8dfebe8015e6e5ee3dc5be',
       '9e61de7e3ef7e99896060d76e48df65d',
       '59456cc9f0eb749249f39d1f8f633ad3',
       '7af3e2da474486a3519b0cba9dea8ad9',
       '7cb52b1fc31186f200f2ad70fef8d3e4',
       'cbe24747d52ccb72f4fd7190c41aff73',
       '3e6092cf0f56b9c78bcbd539157b9f70',
       '7230bdf5aac37f7e218452287461b3cc',
       'ca26080d8f0fa848c329fe732f5e34e8',
       'b607bf5bab84cb38111d2b6a10164385',
       'eef398550dd9575d23eb2d8be74bd45a',
       '986551a629c57419d4d2b74cdefc34dd',
       '73df0070248804951b5c6ba9537c6fc3',
       'c7858457bc43561ccb96aaa2932cb085',
       'c09d788af5101df1f542712d2968d4df',
       '0e030462875259ec0cb868f7ecf1fd5e',
       '66e460f0a3bf13493f3eeda3d75c61b4',
       'b2545dd62c61d45d55ebaa04d1cb1e23',
       'e3b4b906fc11fd64318e4923a3d4594f',
       '7dc0fd89c290eb0b3e5253d19be59f6f',
       '882ae61d3259507f5c3ce5313f433651',
       '44dcb08478450d530b70de0c5c7c5f4a',
       'bb69b35babb38529a803d3f77d1e7454',
       'd7b39598905ba8e791fe3f1f376d59f9',
       '788dbbaefb68cbb1f4cc56ba5151b085',
       '73c5d3186138770b5ae53055adf10ad9',
       'ab142a566883e92ca907236477173c6c',
       'eb8d25c0cd79b71775e91ed30a8fb8e8',
       '6ad6cc284cdcc1cdd2f06eef8d983913',
       '67f36b3689147d882d2b298fd0715d80',
       'aa52785e49f7b78b96704df4068d9e3d',
       'd725b0198c31ea044c691b51d13656d4',
       '45d0bf74166b507caa830564130b5ba0',
       'e2613182a3d5b61459d52f24823134fb',
       'ee0698233ed7e7c83c26c24f3efe315d',
       'bfb85a2851757334da980ac9893a6261',
       'a9d8f831888820cd641dcd5ca9fea4e8',
       '9f6e8441548dd40516cdb98f1b29c3d5',
       '0f4dbfe93fbadcce71e1edce3a3e30f0',
       '29fffacd0907d0944b7af35086efdb43',
       '518ab602253d96d56c7e45d473572f58',
       '2bc14ec16ec416f08e39fed48eda7f2d',
       '12ad6d9a5da40908f6741145e1a93443',
       '240ab905c5d99c074894c0fb5a27979f',
       'b61d1388a17e3f547d2bc218df02335b',
       '6d0af4d8b482cc38d72acafc37bdd8f1',
       '840c7da1a74c54e903c0c6b86d44deed',
       '014fcf6bd5cd4c7ee29fb3bb618c445e',
       'dfa3272f8e1bad4867677dfca2d061f3',
       'ae4c65e3aee93bc068c671453b8aaea4',
       'afbefb1506762049cf9e9bbe2ce06ecc',
       '09ff539a621711667c43eba6a3bd8466',
       'bef4997c604c1f7f307936cc0fb143c1',
       '5f4bceafafc1903556735cb7f2842e78',
       '661e3bba6bdb874638367462b49ae590',
       '96aca2f53bcaed6f466449f7fb18ae75',
       'e64befe356dccc6ed0073c124147269f',
       'b01cedfa96d891427058852f0625e9ee',
       '4f0aa1e91719362daf498003e6ad4177',
       '090820212dfd8022d676e480bed6a61d',
       '4a411619ffbd1bb6180c44ca6e16639d',
       'dc9f66a56b89e4278d921898a861a29a',
       'ef60a683caacd212b1cc7b356283c2de',
       '61a15da36ca0448be0565f8ee41dd37e',
       '86047e935e01608082bdae92e41a11db',
       '7167af17015615b513d5b429758969a2',
       'e987172c2818cc16b2555bc130ac5fac',
       '03706dca83513062fe74967a71b5fc78',
       '8d0e7a8e1b1fb5343135045cb7c21542',
       'b77b1c083bc9bd1bbceccc2346cd02f4',
       'd99e1e07cdfcb6400db4c4eef7b0b15b',
       '0836db91ee8fd88d685b5a57bed9ede0',
       '22f8b1ebff0ccf1828c7179dbf84d983',
       '1631507f13bd83d2f01e4fea424c852b',
       '3128a1273a207ae946c4dd1e23c86fed',
       '4b2c89ca021d0de0c060387a34588316',
       '7a81b0d1231e9ed0c2ff4237f49e5dc0',
       'ff09b38ea3889c433325e313807936ea',
       '9032c8a4a91bb344eb53711d9fd71361',
       '945d5b64caf3027a69078cd3254657a7',
       'b71e22caa2e31ed1309fd01850d79ea4',
       '7ee185224a0391c3ef0865347c1898e5',
       'bb1c86c0b1cd8da99fbd48d798abcca0',
       '4c50dcc50f1512f46096d6ef0142c4a9',
       '44483ca1c9223756ee0ee71c0676d3a3',
       '2c484c3b1f80b8c735fcccb9b1f0f0e6',
       '66a5ffd1047bfd6230ac214e03257bae',
       '46255a421f244cd985f138a63d77d09c',
       'f524a09994004b2dabb3d13cf1a041fb',
       '96cadd6d137bc9726fe1fae279d48631',
       'd8dee61c2034d6d075997acef1870e9b',
       '6962734c72522e70e852a2a77d21a730',
       '1574ed2c73e4465c572f68dd77528203',
       'e3e0c67c30ba9f25ab3a0f8e293737ed',
       'b17a4e7b997ea645dd323bb1bed802ac',
       '11f683ded5ddeecdad0b81b3124c3395',
       '0538b3ea14af3cc3ee6bdaf940367cee',
       '51f906f965ca71722df2059f9a7c1b62',
       '27f0ec8644d62c85b25674aaa6d1124c',
       '6972a2007571907bdd466492ffa86638',
       '82758517d6c9cc65c509781f1e14e9f2',
       '92785d022b4e0e6b7cafc45f87a281fb',
       '338f1838eb9cd29b59c9c2f4ee158f15',
       '24aba57735be13fd785bc04d1a8812e4',
       'dc265762419b1b4a46eb0a242e713684',
       '8a27d3427a61686ec37357b5ccf24425',
       '6868e3f08c6acd37b48c785aedddfdb7',
       '43afa94fdd01b7f2a67f3776a8df0d71',
       '1dcd65bb5dd967d7b4c6b0223cefb838',
       'e68658c105f5425a8839abcbc722d160',
       'c2e65424d0c3ca6c8c87576a7307eb90',
       '61e9a389f1bef5181fc96e33f0dc16a6',
       '5cebe3c91f03e5d52a1951b3ce8354cd',
       '645fd9f79f14fad6e8a79fbc94dae528',
       '24b1fcad996ffb1ead90e324f264b783',
       '086f97beca2bb06567d542af191fa7a9',
       'e3c816666a7d2a1e7fbf02651e550b78',
       'c321936f167cdd14866ac591eea36f38',
       '10dbe0fbaa2c505123c17fdc34a63c56',
       'dcea59ebbc38fcdee1974bbe56dc3755',
       '1a2ece70966710dec441aa587993b5b4',
       'c31d2c7898c24ea73ab60e0660fd693f',
       '69c2f05e34d543dc71cfe745bfac8499',
       'ed4359e101555dd1a1b90dea86938a9f',
       '7ce49c8945602088c4c4ca3e0ceb8244',
       'aba85c958ea6774626886041ac01acf1',
       'ae91ef458ab29ff95a0defb53fa030e9',
       'ef5d149e671d0d67a962eceb26d972c8',

In [62]:
order_items[order_items['product_id'].isin(missing_product_ids)]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
123,0046e1d57f4c07c8c92ab26be8c3dfc0,1,ff6caf9340512b8bf6d2a2a6df032cfa,38e6dada03429a47197d5d584d793b41,2017-10-02 15:49:17,7.79,7.78
125,00482f2670787292280e0a8153d82467,1,a9c404971d1a5b1cbc2e4070e02731fd,702835e4b785b67a084280efca355756,2017-02-17 16:18:07,7.60,10.96
132,004f5d8f238e8908e6864b874eda3391,1,5a848e4ab52fd5445cdc07aab1c40e48,c826c40d7b19f62a09e2d7c5e7295ee2,2018-03-06 09:29:25,122.99,15.61
142,0057199db02d1a5ef41bacbf41f8f63b,1,41eee23c25f7a574dfaf8d5c151dbb12,e5a3438891c0bfdb9394643f95273d8e,2018-01-25 09:07:51,20.30,16.79
171,006cb7cafc99b29548d4f412c7f9f493,1,e10758160da97891c2fdcbc35f0f031d,323ce52b5b81df2cd804b017b7f09aa7,2018-02-22 13:35:28,56.00,14.14
...,...,...,...,...,...,...,...
112306,ff24fec69b7f3d30f9dc1ab3aee7c179,1,5a848e4ab52fd5445cdc07aab1c40e48,c826c40d7b19f62a09e2d7c5e7295ee2,2018-02-01 02:40:12,122.99,15.61
112333,ff3024474be86400847879103757d1fd,1,f9b1795281ce51b1cf39ef6d101ae8ab,3771c85bac139d2344864ede5d9341e3,2017-11-21 03:55:39,39.90,9.94
112350,ff3a45ee744a7c1f8096d2e72c1a23e4,1,b61d1388a17e3f547d2bc218df02335b,07017df32dc5f2f1d2801e579548d620,2017-05-10 10:15:19,139.00,21.42
112438,ff7b636282b98e0aa524264b295ed928,1,431df35e52c10451171d8037482eeb43,6cd68b3ed6d59aaa9fece558ad360c0a,2018-02-22 15:35:35,49.90,15.11
112501,ffa5e4c604dea4f0a59d19cc2322ac19,2,bd421826916d3e1d445cb860cea3c0fb,59cd88080b93f3c18508673122d26169,2017-12-11 08:41:20,29.99,15.10

In [63]:
products.shape

(32340, 9)

In [64]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              4
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [65]:
order_items['product_id'].isin(products['product_id']).all()

np.False_

In [66]:
products = pd.read_csv(
    "C:/Users/saran/guvi project/cart2insights/data/raw/olist_products_dataset.csv"
)

In [67]:
print(products.shape)
print(products.isnull().sum())

(32951, 9)
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [68]:
order_items['product_id'].isin(products['product_id']).all()

np.True_

In [69]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [70]:
products['product_category_name'] = products['product_category_name'].fillna('unknown')

In [71]:
products['product_name_lenght'] = products['product_name_lenght'].fillna(0)

products['product_description_lenght'] = products['product_description_lenght'].fillna(0)

products['product_photos_qty'] = products['product_photos_qty'].fillna(0)

In [72]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              2
product_length_cm             2
product_height_cm             2
product_width_cm              2
dtype: int64

In [73]:
order_items['product_id'].isin(products['product_id']).all()

np.True_

In [74]:
products[products['product_weight_g'].isnull()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,unknown,0.0,0.0,0.0,NaN,NaN,NaN,NaN

In [75]:
(products['product_weight_g'] == 0).sum()

np.int64(4)

In [77]:
products.loc[products['product_weight_g'] == 0, 'product_weight_g'] = np.nan
products['product_weight_g'].isnull().sum()

np.int64(6)

In [78]:
order_items['product_id'].isin(products['product_id']).all()

np.True_

In [79]:
print("Customers:", customers.isnull().sum().sum())
print("Orders:", orders.isnull().sum().sum())
print("Order Items:", order_items.isnull().sum().sum())
print("Payments:", order_payments.isnull().sum().sum())
print("Reviews:", order_reviews.isnull().sum().sum())
print("Products:", products.isnull().sum().sum())
print("Sellers:", sellers.isnull().sum().sum())
print("Geolocation:", geolocation.isnull().sum().sum())
print("Categories:", product_categories.isnull().sum().sum())

Customers: 0
Orders: 4908
Order Items: 0
Payments: 0
Reviews: 0
Products: 12
Sellers: 0
Geolocation: 0
Categories: 0

In [80]:
print("Customer FK:", orders['customer_id'].isin(customers['customer_id']).all())
print("Order FK:", order_items['order_id'].isin(orders['order_id']).all())
print("Payment FK:", order_payments['order_id'].isin(orders['order_id']).all())
print("Review FK:", order_reviews['order_id'].isin(orders['order_id']).all())
print("Product FK:", order_items['product_id'].isin(products['product_id']).all())
print("Seller FK:", order_items['seller_id'].isin(sellers['seller_id']).all())

Customer FK: True
Order FK: True
Payment FK: True
Review FK: True
Product FK: True
Seller FK: True

In [3]:

reviews_check = pd.read_csv(
    r"C:\Users\saran\guvi project\cart2insights\data\cleaned\order_reviews_cleaned.csv"
)

print("Rows:", len(reviews_check))
print("Columns:", reviews_check.columns.tolist())

Rows: 99224
Columns: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

In [9]:
import os

cleaned_path = "C:/Users/saran/guvi project/cart2insights/data/cleaned"

os.makedirs(cleaned_path, exist_ok=True)

In [82]:
customers.to_csv(f"{cleaned_path}/customers_cleaned.csv", index=False)

orders.to_csv(f"{cleaned_path}/orders_cleaned.csv", index=False)

order_items.to_csv(f"{cleaned_path}/order_items_cleaned.csv", index=False)

order_payments.to_csv(f"{cleaned_path}/order_payments_cleaned.csv", index=False)

order_reviews.to_csv(f"{cleaned_path}/order_reviews_cleaned.csv", index=False)

products.to_csv(f"{cleaned_path}/products_cleaned.csv", index=False)

sellers.to_csv(f"{cleaned_path}/sellers_cleaned.csv", index=False)

geolocation.to_csv(f"{cleaned_path}/geolocation_cleaned.csv", index=False)

product_categories.to_csv(
    f"{cleaned_path}/product_category_name_translation_cleaned.csv",
    index=False
)

In [83]:
os.listdir(cleaned_path)

['customers_cleaned.csv',
 'geolocation_cleaned.csv',
 'orders_cleaned.csv',
 'order_items_cleaned.csv',
 'order_payments_cleaned.csv',
 'order_reviews_cleaned.csv',
 'products_cleaned.csv',
 'product_category_name_translation_cleaned.csv',
 'sellers_cleaned.csv']

In [10]:
os.makedirs(cleaned_path, exist_ok=True)

In [11]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

In [12]:
engine = create_engine(
    "mysql+pymysql://root:abc123@localhost/cart2insights"
)

In [14]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

password = quote_plus("YOUR_MYSQL_PASSWORD")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/cart2insights"
)

print("Connected successfully!")

Connected successfully!

In [15]:
reviews.to_sql(
    "order_reviews",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=1000
)

print("Import completed!")

OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [16]:
import pandas as pd
import os

file_path = r"C:\Users\saran\guvi project\cart2insights\data\cleaned\order_reviews_cleaned.csv"

reviews = pd.read_csv(file_path)

output_folder = r"C:\Users\saran\guvi project\cart2insights\data\reviews_parts"
os.makedirs(output_folder, exist_ok=True)

chunk_size = 10000

for i in range(0, len(reviews), chunk_size):
    chunk = reviews.iloc[i:i + chunk_size]
    file_number = i // chunk_size + 1

    chunk.to_csv(
        f"{output_folder}/reviews_part_{file_number}.csv",
        index=False
    )

print("Total rows:", len(reviews))
print("Files created:", len(range(0, len(reviews), chunk_size)))

Total rows: 99224
Files created: 10

In [ ]:
import pandas as pd

reviews = pd.read_csv(
    r"C:\Users\saran\guvi project\cart2insights\data\cleaned\order_reviews_cleaned.csv"
)

orders = pd.read_csv(
    r"C:\Users\saran\guvi project\cart2insights\data\cleaned\orders_cleaned.csv"
)

print(reviews.shape)
print(orders.shape)