In [1]:
pip install scipy statsmodels

Requirement already satisfied: scipy in c:\users\saran\anaconda3\lib\site-packages (1.16.3)
Requirement already satisfied: statsmodels in c:\users\saran\anaconda3\lib\site-packages (0.14.5)
Requirement already satisfied: numpy<2.6,>=1.25.2 in c:\users\saran\anaconda3\lib\site-packages (from scipy) (2.3.5)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\saran\anaconda3\lib\site-packages (from statsmodels) (2.3.3)
Requirement already satisfied: patsy>=0.5.6 in c:\users\saran\anaconda3\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in c:\users\saran\anaconda3\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saran\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\saran\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saran\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\saran\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

from scipy.stats import ttest_ind
from scipy.stats import levene
from scipy.stats import chi2_contingency
from scipy.stats import f_oneway

from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [3]:
CLEANED_PATH = r"C:\Users\saran\guvi project\cart2insights\data\cleaned"

orders = pd.read_csv(
    CLEANED_PATH + r"\orders_cleaned.csv"
)

reviews = pd.read_csv(
    CLEANED_PATH + r"\order_reviews_cleaned.csv"
)

In [4]:
orders["order_delivered_customer_date"] = pd.to_datetime(
    orders["order_delivered_customer_date"]
)

orders["order_estimated_delivery_date"] = pd.to_datetime(
    orders["order_estimated_delivery_date"]
)

orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"]
)

In [5]:
orders["delivery_status"] = np.nan

valid = (
    orders["order_delivered_customer_date"].notna()
    &
    orders["order_estimated_delivery_date"].notna()
)

orders.loc[
    valid &
    (
        orders["order_delivered_customer_date"]
        <= orders["order_estimated_delivery_date"]
    ),
    "delivery_status"
] = "On Time"

orders.loc[
    valid &
    (
        orders["order_delivered_customer_date"]
        > orders["order_estimated_delivery_date"]
    ),
    "delivery_status"
] = "Delayed"

C:\Users\saran\AppData\Local\Temp\ipykernel_1056\3084923695.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'On Time' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  orders.loc[

In [6]:
review_delivery = reviews.merge(
    orders[["order_id", "delivery_status"]],
    on="order_id",
    how="inner"
)

review_delivery = review_delivery[
    review_delivery["delivery_status"].isin(
        ["On Time", "Delayed"]
    )
]

display(
    review_delivery.groupby("delivery_status")["review_score"]
    .agg(["count", "mean", "std"])
)

                 count      mean       std
delivery_status
Delayed           7701  2.566550  1.658240
On Time          88658  4.293578  1.147938

In [7]:
on_time_reviews = review_delivery.loc[
    review_delivery["delivery_status"] == "On Time",
    "review_score"
].dropna()

delayed_reviews = review_delivery.loc[
    review_delivery["delivery_status"] == "Delayed",
    "review_score"
].dropna()

t_stat, p_value = ttest_ind(
    on_time_reviews,
    delayed_reviews,
    equal_var=False
)

print("Welch t-statistic:", t_stat)
print("p-value:", p_value)

Welch t-statistic: 89.55081413351807
p-value: 0.0

In [8]:
if p_value < 0.05:
    print(
        "There is a statistically significant difference "
        "in review scores between on-time and delayed deliveries."
    )
else:
    print(
        "There is no statistically significant difference "
        "in review scores."
    )

There is a statistically significant difference in review scores between on-time and delayed deliveries.

In [9]:
order_items = pd.read_csv(
    CLEANED_PATH + r"\order_items_cleaned.csv"
)

products = pd.read_csv(
    CLEANED_PATH + r"\products_cleaned.csv"
)

translation = pd.read_csv(
    CLEANED_PATH + r"\product_category_name_translation_cleaned.csv"
)

In [10]:
items = order_items.merge(
    products[[
        "product_id",
        "product_category_name"
    ]],
    on="product_id",
    how="left"
)

items = items.merge(
    translation,
    on="product_category_name",
    how="left"
)

items["category"] = items[
    "product_category_name_english"
].fillna(
    items["product_category_name"]
).fillna("unknown")

In [11]:
items["order_value"] = (
    items["price"] +
    items["freight_value"]
)

In [13]:
category_value = (
    items
    .groupby(
        ["order_id", "category"],
        as_index=False
    )["price"]
    .sum()
)

primary_category = (
    category_value
    .sort_values(
        ["order_id", "price"],
        ascending=[True, False]
    )
    .drop_duplicates("order_id")
)

primary_category = primary_category[
    ["order_id", "category"]
]

print("Primary category created successfully!")
print(primary_category.head())

Primary category created successfully!
                           order_id         category
0  00010242fe8c5a6d1ba2dd792cb16214       cool_stuff
1  00018f77f2f0320c557190d7a144bdd3         pet_shop
2  000229ec398224ef6ca0657da4fc703e  furniture_decor
3  00024acbcdf0a6daa1e931b038114c75        perfumery
4  00042b26cf59d7ce69dfabb4e55b4fd9     garden_tools

In [14]:
order_values = (
    items
    .groupby("order_id", as_index=False)
    .agg(
        order_value=("order_value", "sum")
    )
)

h2_data = order_values.merge(
    primary_category,
    on="order_id",
    how="inner"
)

display(
    h2_data.groupby("category")["order_value"]
    .agg(["count", "mean", "std"])
    .sort_values("mean", ascending=False)
)

                                       count         mean         std
category
computers                                181  1286.948011  737.143982
small_appliances_home_oven_and_coffee     75   669.247600  629.511844
home_appliances_2                        234   529.747521  559.760451
agro_industry_and_commerce               182   430.626758  616.049081
musical_instruments                      624   336.697404  485.185889
...                                      ...          ...         ...
food                                     444    81.647748   51.169325
cds_dvds_musicals                         12    79.582500   25.944240
diapers_and_hygiene                       27    79.306296   46.828592
flowers                                   28    55.972857   28.543192
home_comfort_2                            22    51.427727   48.788875

[74 rows x 3 columns]

In [15]:
category_counts = (
    h2_data["category"]
    .value_counts()
)

valid_categories = category_counts[
    category_counts >= 30
].index

h2_test = h2_data[
    h2_data["category"].isin(valid_categories)
]

In [16]:
groups = [
    group["order_value"].values
    for _, group in h2_test.groupby("category")
]

f_stat, p_value = f_oneway(*groups)

print("ANOVA F-statistic:", f_stat)
print("p-value:", p_value)

ANOVA F-statistic: 173.5729452830601
p-value: 0.0

In [17]:
if p_value < 0.05:
    print(
        "There is a statistically significant difference "
        "in average order value across product categories."
    )
else:
    print(
        "There is no statistically significant difference "
        "in average order value across product categories."
    )

There is a statistically significant difference in average order value across product categories.

In [18]:
tukey = pairwise_tukeyhsd(
    endog=h2_test["order_value"],
    groups=h2_test["category"],
    alpha=0.05
)

print(tukey)

                                     Multiple Comparison of Means - Tukey HSD, FWER=0.05
==============================================================================================================================
                 group1                                  group2                  meandiff  p-adj    lower      upper    reject
------------------------------------------------------------------------------------------------------------------------------
             agro_industry_and_commerce                        air_conditioning  -185.4402    0.0  -268.9542  -101.9262   True
             agro_industry_and_commerce                                     art  -288.9926    0.0  -377.0469  -200.9383   True
             agro_industry_and_commerce                                   audio  -269.4359    0.0  -348.0488  -190.8231   True
             agro_industry_and_commerce                                    auto  -253.9004    0.0  -319.0139  -188.7869   True
             agro_industry_and_commerce                                    baby  -261.1203    0.0  -326.7703  -195.4703   True
             agro_industry_and_commerce                          bed_bath_table  -297.0114    0.0  -361.2655  -232.7573   True
             agro_industry_and_commerce                  books_general_interest  -320.4574    0.0  -394.6046  -246.3102   True
             agro_industry_and_commerce                          books_imported  -327.9586    0.0  -461.9604  -193.9569   True
             agro_industry_and_commerce                         books_technical   -340.036    0.0  -423.1418  -256.9303   True
             agro_industry_and_commerce                      christmas_supplies  -336.4751    0.0  -435.5105  -237.4397   True
             agro_industry_and_commerce                              cine_photo  -301.2536    0.0  -426.0184  -176.4888   True
             agro_industry_and_commerce                               computers   856.3213    0.0   766.1997   946.4428   True
             agro_industry_and_commerce                   computers_accessories  -271.5867    0.0  -336.0867  -207.0868   True
             agro_industry_and_commerce                          consoles_games  -262.8352    0.0  -331.7342  -193.9362   True
             agro_industry_and_commerce         construction_tools_construction  -206.4272    0.0  -277.4703  -135.3841   True
             agro_industry_and_commerce               construction_tools_lights  -225.8437    0.0  -310.9347  -140.7527   True
             agro_industry_and_commerce               construction_tools_safety    -158.34    0.0  -251.0734   -65.6066   True
             agro_industry_and_commerce                              cool_stuff  -230.8967    0.0  -296.1228  -165.6706   True
             agro_industry_and_commerce                costruction_tools_garden  -264.1738    0.0  -353.1046   -175.243   True
             agro_industry_and_commerce                 costruction_tools_tools  -245.7384    0.0  -353.6656  -137.8112   True
             agro_industry_and_commerce                                  drinks  -334.2082    0.0  -415.3414   -253.075   True
             agro_industry_and_commerce                            dvds_blu_ray  -304.8506    0.0  -434.3018  -175.3993   True
             agro_industry_and_commerce                             electronics   -348.903    0.0  -414.7847  -283.0213   True
             agro_industry_and_commerce                  fashio_female_clothing  -342.7939    0.0  -495.9146  -189.6731   True
             agro_industry_and_commerce                fashion_bags_accessories  -331.2783    0.0  -397.9648  -264.5918   True
             agro_industry_and_commerce                   fashion_male_clothing  -314.4193    0.0  -417.5242  -211.3145   True
             agro_industry_and_commerce                           fashion_shoes  -311.3718    0.0  -395.9095   -226.834   True
             agro_industry_and_commerce                 fashion_underwear_beach  -335.9347    0.0  -436.6379  -235.2315   True
             agro_industry_and_commerce                         fixed_telephony   -134.211    0.0  -220.5032   -47.9189   True
             agro_industry_and_commerce                                    food   -348.979    0.0  -424.5422  -273.4158   True
             agro_industry_and_commerce                              food_drink  -343.0523    0.0  -428.7272  -257.3775   True
             agro_industry_and_commerce                       furniture_bedroom   -169.087    0.0  -277.7527   -60.4212   True
             agro_industry_and_commerce                         furniture_decor  -288.5349    0.0  -353.0807  -223.9891   True
             agro_industry_and_commerce                   furniture_living_room  -219.9757    0.0  -296.2746  -143.6768   True
             agro_industry_and_commerce       furniture_mattress_and_upholstery  -272.7704    0.0  -425.8912  -119.6497   True
             agro_industry_and_commerce                            garden_tools  -263.0483    0.0  -328.3307  -197.7658   True
             agro_industry_and_commerce                           health_beauty  -266.7658    0.0   -331.058  -202.4735   True
             agro_industry_and_commerce                         home_appliances  -306.2937    0.0  -377.1068  -235.4807   True
             agro_industry_and_commerce                       home_appliances_2    99.1208 0.0028    14.2705    183.971   True
             agro_industry_and_commerce                            home_confort  -252.6546    0.0  -330.7753   -174.534   True
             agro_industry_and_commerce                       home_construction  -227.0485    0.0  -301.8479  -152.2492   True
             agro_industry_and_commerce                              housewares  -297.0279    0.0  -361.6528   -232.403   True
             agro_industry_and_commerce          industry_commerce_and_business  -227.3038    0.0   -312.314  -142.2937   True
             agro_industry_and_commerce kitchen_dining_laundry_garden_furniture  -192.0387    0.0  -276.1248  -107.9525   True
             agro_industry_and_commerce                     luggage_accessories  -264.2874    0.0  -333.3239  -195.2509   True
             agro_industry_and_commerce                            market_place  -308.6871    0.0   -390.783  -226.5911   True
             agro_industry_and_commerce                                   music  -246.7373    0.0  -403.3372   -90.1374   True
             agro_industry_and_commerce                     musical_instruments   -93.9294 0.0002  -166.2546   -21.6041   True
             agro_industry_and_commerce                        office_furniture  -160.2054    0.0  -228.2504   -92.1604   True
             agro_industry_and_commerce                          party_supplies  -293.2594    0.0  -446.3801  -140.1386   True
             agro_industry_and_commerce                               perfumery  -286.7663    0.0  -352.2189  -221.3137   True
             agro_industry_and_commerce                                pet_shop  -281.4634    0.0  -348.4153  -214.5115   True
             agro_industry_and_commerce                  signaling_and_security  -229.7647    0.0  -326.4721  -133.0573   True
             agro_industry_and_commerce                        small_appliances  -101.8639    0.0  -174.1371   -29.5907   True
             agro_industry_and_commerce   small_appliances_home_oven_and_coffee   238.6208    0.0   120.8194   356.4222   True
             agro_industry_and_commerce                          sports_leisure  -280.1581    0.0  -344.5452  -215.7709   True
             agro_industry_and_commerce                              stationery  -309.4645    0.0  -375.5827  -243.3463   True
             agro_industry_and_commerce                  tablets_printing_image  -317.8186    0.0  -434.0046  -201.6325   True
             agro_industry_and_commerce                               telephony  -336.2622    0.0  -401.2709  -271.2535   True
             agro_industry_and_commerce                                    toys  -285.2435    0.0  -350.3601   -220.127   True
             agro_industry_and_commerce                                 unknown    -285.01    0.0  -352.6302  -217.3898   True
             agro_industry_and_commerce                           watches_gifts  -197.5662    0.0  -262.2287  -132.9038   True
                       air_conditioning                                     art  -103.5524 0.0003  -184.9687    -22.136   True
                       air_conditioning                                   audio   -83.9957 0.0021  -155.0945   -12.8969   True
                       air_conditioning                                    auto   -68.4602 0.0009  -124.2709   -12.6495   True
                       air_conditioning                                    baby   -75.6801 0.0001  -132.1158   -19.2443   True
                       air_conditioning                          bed_bath_table  -111.5712    0.0  -166.3768   -56.7656   True
                       air_conditioning                  books_general_interest  -135.0172    0.0  -201.1449   -68.8895   True
                       air_conditioning                          books_imported  -142.5184   0.01  -272.2549    -12.782   True
                       air_conditioning                         books_technical  -154.5958    0.0  -230.6328   -78.5588   True
                       air_conditioning                      christmas_supplies  -151.0349    0.0  -244.2179   -57.8519   True
                       air_conditioning                              cine_photo  -115.8134 0.0842  -235.9855     4.3586  False
                       air_conditioning                               computers  1041.7615    0.0   958.1136  1125.4093   True
                       air_conditioning                   computers_accessories   -86.1465    0.0  -141.2402   -31.0529   True
                       air_conditioning                          consoles_games    -77.395 0.0002  -137.5792   -17.2108   True
                       air_conditioning         construction_tools_construction    -20.987    1.0   -83.6144    41.6404  False
                       air_conditioning               construction_tools_lights   -40.4035 0.9995  -118.6054    37.7985  False
                       air_conditioning               construction_tools_safety    27.1002    1.0   -59.3553   113.5557  False
                       air_conditioning                              cool_stuff   -45.4565 0.4486  -101.3985    10.4855  False
                       air_conditioning                costruction_tools_garden   -78.7336 0.0937  -161.0972     3.6299  False
                       air_conditioning                 costruction_tools_tools   -60.2982 0.9895  -162.8815    42.2851  False
                       air_conditioning                                  drinks   -148.768    0.0   -222.644    -74.892   True
                       air_conditioning                            dvds_blu_ray  -119.4103 0.0948  -244.4411     5.6204  False
                       air_conditioning                             electronics  -163.4628    0.0  -220.1678  -106.7577   True
                       air_conditioning                  fashio_female_clothing  -157.3537 0.0217  -306.7559    -7.9514   True
                       air_conditioning                fashion_bags_accessories  -145.8381    0.0  -203.4763   -88.1999   True
                       air_conditioning                   fashion_male_clothing  -128.9791 0.0001  -226.4762   -31.4821   True
                       air_conditioning                           fashion_shoes  -125.9315    0.0  -203.5312   -48.3319   True
                       air_conditioning                 fashion_underwear_beach  -150.4945    0.0  -245.4481   -55.5408   True
                       air_conditioning                         fixed_telephony    51.2292 0.9464    -28.278   130.7364  False
                       air_conditioning                                    food  -163.5388    0.0  -231.2504   -95.8272   True
                       air_conditioning                              food_drink  -157.6121    0.0   -236.449   -78.7752   True
                       air_conditioning                       furniture_bedroom    16.3532    1.0   -87.0069   119.7133  False
                       air_conditioning                         furniture_decor  -103.0947    0.0   -158.242   -47.9474   True
                       air_conditioning                   furniture_living_room   -34.5355 0.9997  -103.0672    33.9962  False
                       air_conditioning       furniture_mattress_and_upholstery   -87.3302 0.9906  -236.7325     62.072  False
                       air_conditioning                            garden_tools   -77.6081    0.0  -133.6158   -21.6003   True
                       air_conditioning                           health_beauty   -81.3256    0.0  -136.1759   -26.4752   True
                       air_conditioning                         home_appliances  -120.8535    0.0  -183.2198   -58.4872   True
                       air_conditioning                       home_appliances_2    284.561    0.0    206.621   362.5009   True
                       air_conditioning                            home_confort   -67.2144 0.0979  -137.7687     3.3398  False
                       air_conditioning                       home_construction   -41.6083 0.9695  -108.4665    25.2498  False
                       air_conditioning                              housewares  -111.5877    0.0  -166.8276   -56.3478   True
                       air_conditioning          industry_commerce_and_business   -41.8636 0.9987  -119.9776    36.2503  False
                       air_conditioning kitchen_dining_laundry_garden_furniture    -6.5985    1.0   -83.7058    70.5089  False
                       air_conditioning                     luggage_accessories   -78.8472 0.0002  -139.1888   -18.5056   True
                       air_conditioning                            market_place  -123.2469    0.0  -198.1789   -48.3148   True
                       air_conditioning                                   music   -61.2971    1.0  -214.2631    91.6689  False
                       air_conditioning                     musical_instruments    91.5109    0.0    27.4327    155.589   True
                       air_conditioning                        office_furniture    25.2348    1.0   -33.9698    84.4394  False
                       air_conditioning                          party_supplies  -107.8192 0.7749  -257.2214    41.5831  False
                       air_conditioning                               perfumery  -101.3261    0.0   -157.532   -45.1201   True
                       air_conditioning                                pet_shop   -96.0232    0.0  -153.9682   -38.0782   True
                       air_conditioning                  signaling_and_security   -44.3245 0.9999  -135.0294    46.3805  False
                       air_conditioning                        small_appliances    83.5763 0.0002    19.5569   147.5957   True
                       air_conditioning   small_appliances_home_oven_and_coffee   424.0611    0.0   311.1352   536.9869   True
                       air_conditioning                          sports_leisure   -94.7178    0.0  -149.6794   -39.7563   True
                       air_conditioning                              stationery  -124.0243    0.0  -181.0039   -67.0446   True
                       air_conditioning                  tablets_printing_image  -132.3783 0.0018   -243.618   -21.1387   True
                       air_conditioning                               telephony   -150.822    0.0  -206.5104   -95.1336   True
                       air_conditioning                                    toys   -99.8033    0.0  -155.6176   -43.9891   True
                       air_conditioning                                 unknown   -99.5698    0.0  -158.2857   -40.8538   True
                       air_conditioning                           watches_gifts    -12.126    1.0   -67.4098    43.1578  False
                                    art                                   audio    19.5567    1.0   -56.8241    95.9374  False
                                    art                                    auto    35.0922 0.9959   -27.3082    97.4926  False
                                    art                                    baby    27.8723    1.0   -35.0877    90.8323  False
                                    art                          bed_bath_table    -8.0188    1.0   -69.5219    53.4843  False
                                    art                  books_general_interest   -31.4648    1.0  -103.2412    40.3115  False
                                    art                          books_imported   -38.9661    1.0  -171.6707    93.7386  False
                                    art                         books_technical   -51.0434 0.9624   -132.041    29.9541  False
                                    art                      christmas_supplies   -47.4825 0.9999  -144.7556    49.7905  False
                                    art                              cine_photo    -12.261    1.0  -135.6316   111.1095  False
                                    art                               computers  1145.3138    0.0  1057.1326  1233.4951   True
                                    art                   computers_accessories    17.4058    1.0   -44.3541    79.1657  False
                                    art                          consoles_games    26.1574    1.0   -40.1835    92.4982  False
                                    art         construction_tools_construction    82.5654 0.0014    14.0003   151.1304   True
                                    art               construction_tools_lights    63.1489 0.6415   -19.8843   146.1821  False
                                    art               construction_tools_safety   130.6526    0.0    39.8037   221.5015   True
                                    art                              cool_stuff    58.0959 0.1329    -4.4219   120.6137  False
                                    art                costruction_tools_garden    24.8188    1.0   -62.1452   111.7827  False
                                    art                 costruction_tools_tools    43.2542    1.0   -63.0582   149.5665  False
                                    art                                  drinks   -45.2156 0.9939   -124.188    33.7568  False
                                    art                            dvds_blu_ray    -15.858    1.0   -143.966     112.25  False
                                    art                             electronics   -59.9104 0.1044   -123.112     3.2911  False
                                    art                  fashio_female_clothing   -53.8013    1.0  -205.7881    98.1856  False
                                    art                fashion_bags_accessories   -42.2857  0.923  -106.3258    21.7544  False
                                    art                   fashion_male_clothing   -25.4268    1.0  -126.8401    75.9865  False
                                    art                           fashion_shoes   -22.3792    1.0  -104.8454     60.087  False
                                    art                 fashion_underwear_beach   -46.9421    1.0  -145.9127    52.0284  False
                                    art                         fixed_telephony   154.7815    0.0    70.5179   239.0452   True
                                    art                                    food   -59.9864 0.4254  -133.2246    13.2518  False
                                    art                              food_drink   -54.0598 0.9437  -137.6912    29.5717  False
                                    art                       furniture_bedroom   119.9056 0.0068    12.8436   226.9677   True

In [19]:
payments = pd.read_csv(
    CLEANED_PATH + r"\order_payments_cleaned.csv"
)

orders = pd.read_csv(
    CLEANED_PATH + r"\orders_cleaned.csv"
)

In [20]:
payment_order = (
    payments
    .sort_values("payment_sequential")
    .drop_duplicates("order_id")
)

h3_data = payment_order.merge(
    orders[["order_id", "order_status"]],
    on="order_id",
    how="inner"
)

In [21]:
contingency_table = pd.crosstab(
    h3_data["payment_type"],
    h3_data["order_status"]
)

display(contingency_table)

order_status,approved,canceled,created,delivered,invoiced,processing,shipped,unavailable
payment_type,,,,,,,,
boleto,0,95,2,19191,67,70,209,150
credit_card,2,444,3,74303,239,222,848,443
debit_card,0,7,0,1485,6,2,22,6
not_defined,0,3,0,0,0,0,0,0
voucher,0,76,0,1498,2,7,28,10

In [22]:
chi2, p_value, dof, expected = chi2_contingency(
    contingency_table
)

print("Chi-square statistic:", chi2)
print("Degrees of freedom:", dof)
print("p-value:", p_value)

Chi-square statistic: 939.509784002784
Degrees of freedom: 28
p-value: 8.714660119444278e-180

In [23]:
if p_value < 0.05:
    print(
        "There is a statistically significant association "
        "between payment method and order status."
    )
else:
    print(
        "There is no statistically significant association "
        "between payment method and order status."
    )

There is a statistically significant association between payment method and order status.

In [24]:
groups = [
    group["order_value"].values
    for _, group in h2_test.groupby("category")
]

h2_f_stat, h2_p_value = f_oneway(*groups)

print("H2 ANOVA F-statistic:", h2_f_stat)
print("H2 ANOVA p-value:", h2_p_value)

H2 ANOVA F-statistic: 173.5729452830601
H2 ANOVA p-value: 0.0

In [25]:
if h2_p_value < 0.05:
    print(
        "There is a statistically significant difference "
        "in average order value across product categories."
    )
else:
    print(
        "There is no statistically significant difference "
        "in average order value across product categories."
    )

There is a statistically significant difference in average order value across product categories.